# Generated by Django 4.1.2 on 2023-02-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
