# Generated by Django 4.1.2 on 2023-04-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_likepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='penguin.jfif', upload_to='post_images'),
        ),
    ]
