# Generated by Django 4.1.2 on 2023-04-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='first.PNG', upload_to='post_images'),
        ),
    ]
